### ISSUE TITLE
Remove codepath utils by using scribe async methods

### ISSUE THREAD

**Issue by nesquena** [codepath/android-oauth-handler#34]
Remove the use of AsyncTask by leveraging the new async scribe methods to access the tokens? Is this a good idea on Android?

For [getting the request token](https://github.com/codepath/android-oauth-handler/blob/master/app/src/main/java/com/codepath/oauth/OAuthAsyncHttpClient.java#L48-L75), use [getRequestTokenAsync](https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/oauth/OAuth10aService.java#L56).

For [getting the access token](https://github.com/codepath/android-oauth-handler/blob/master/app/src/main/java/com/codepath/oauth/OAuthAsyncHttpClient.java#L82-L127), use [getAccessTokenAsync](https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/oauth/OAuth10aService.java#L116)

cc @rogerhu

**Comment by rogerhu** [comment]
Interestingly enough the call for getRequestTokenAsync() calls into JDKHttpClient, which turns executeAsync into executing in the main thread so you get `Caused by: android.os.NetworkOnMainThreadException` exceptions.

* https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/oauth/OAuthService.java#L90

* https://github.com/scribejava/scribejava/blob/bd9a43018147cd72e5d2d04ad76752c3b4065ae4/scribejava-core/src/main/java/com/github/scribejava/core/httpclient/jdk/JDKHttpClient.java#L37

![image](https://cloud.githubusercontent.com/assets/326857/25329957/bc30d4b8-2892-11e7-9eee-074f2024f9cf.png)

**Comment by rogerhu** [comment]
Looks like the stock version that comes with it doesn't work.

Seems like if you had OkHttp or Ning's [Android Async Http Client](https://github.com/AsyncHttpClient/async-http-client) setup it would do the right thing.   The loopj Android Async Http Client almost seems abandoned so not sure if it's worth to do.

* https://github.com/scribejava/scribejava/blob/master/scribejava-httpclient-okhttp/src/main/java/com/github/scribejava/httpclient/okhttp/OkHttpHttpClient.java  

* https://github.com/scribejava/scribejava/blob/master/scribejava-httpclient-ahc/src/main/java/com/github/scribejava/httpclient/ahc/AhcHttpClient.java as well.

**Comment by rogerhu** [comment]
FYI there is also GenericsUtil (https://github.com/codepath/android-oauth-handler/blob/master/app/src/main/java/com/codepath/oauth/OAuthLoginActivity.java#L46-L49) that is being used with codepath-utils JAR

**Comment by nesquena** [comment]
In that case I'll close this. Thanks for looking into it.

**Comment by rogerhu** [comment]
This is what it takes to get Scribe async tasks working -- https://github.com/scribejava/scribejava/pull/765/files

:)

**Comment by nesquena** [comment]
Okay if they actually merge this then that's great, if not, I'm guessing it may not be worth maintaining our own fork to remove the async calls?
